server:
  port: 81

spring.cloud.vault:
    token: hvs.CAESIPieyILXp-xddGSyPDro3Fc7VSC8L6tLG0zEOqb9b-0CGh4KHGh2cy40SjdsV05UVjBYSHlUMGZlcTdFTUdtYXY
    host: 192.168.1.200
    port: 8200
    scheme: http
    uri: http://192.168.1.200:8200
    connection-timeout: 5000
    read-timeout: 15000
spring.config.import: vault://vshop/gateway/prod