apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-dev-deployment
  labels:
    app: api-gateway-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway-dev
  template:
    metadata:
      labels:
        app: api-gateway-dev
    spec:
      containers:
      - name: api-gateway-dev
        image: vincentbuiwork/api-gateway:dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80