apiVersion: v1
kind: Service
metadata:
  name: api-gateway-dev-service
  labels:
    app: api-gateway-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.101
  externalIPs:
  - 10.24.24.101
  ports:
  - name: http
    port: 83 #local out port
    protocol: TCP
    targetPort: 83 # container port
  selector:
    app: api-gateway-dev #find all pod with app name
  sessionAffinity: None
