apiVersion: v1
kind: Service
metadata:
  name: api-gateway-prod-service
  labels:
    app: api-gateway-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.101
  externalIPs:
  - 10.24.24.101
  ports:
  - name: http
    port: 81 #local out port
    protocol: TCP
    targetPort: 81 # container port
  selector:
    app: api-gateway-prod #find all pod with app name
  sessionAffinity: None
