apiVersion: v1
kind: Service
metadata:
  name: api-gateway-stage-service
  labels:
    app: api-gateway-stage
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.101
  externalIPs:
  - 10.24.24.101
  ports:
  - name: http
    port: 82 #local out port
    protocol: TCP
    targetPort: 82 # container port
  selector:
    app: api-gateway-stage #find all pod with app name
  sessionAffinity: None
