apiVersion: v1
kind: Service
metadata:
  name: api-gateway-stage-service
  labels:
    app: api-gateway-stage
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.101
  externalIPs:
  - 192.168.1.101
  ports:
  - name: http
    port: 8082 #local out port
    protocol: TCP
    targetPort: 8082 # container port
  selector:
    app: api-gateway-stage #find all pod with app name
  sessionAffinity: None
